export const RouteDifficulty = {
    yosemite: {
        name: "Yosemite",
        varName: 'yosemite',
        values: [
            '5.4',
            '5.5',
            '5.6',
            '5.7',
            '5.8',
            '5.9',
            '5.10a',
            '5.10b',
            '5.10c',
            '5.10d',
            '5.11a',
            '5.11b',
            '5.11c',
            '5.11d',
            '5.12a',
            '5.12b',
            '5.12c',
            '5.12d',
            '5.13a',
            '5.13b',
            '5.13c',
            '5.13d',
            '5.14a',
            '5.14b',
            '5.14c',
            '5.14d',
            '5.15a',
            '5.15b',
            '5.15c'
        ]
    },
    french: {
        name: "French",
        varName: 'french',
        values: [
            '4a',
            '4b',
            '4c',
            '5a',
            '5b',
            '5c',
            '6a',
            '6a+',
            '6b',
            '6b+',
            '6c',
            '6c+',
            '7a',
            '7a+',
            '7b',
            '7b+',
            '7c',
            '7c+',
            '8a',
            '8a+',
            '8b',
            '8b+',
            '8c',
            '8c+',
            '9a',
            '9a+',
            '9b',
            '9b+',
        ]
    },
    australian: {
        name: "Australian",
        varName: 'australian',
        values: [
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
            '22',
            '23',
            '24',
            '25',
            '26',
            '27',
            '28',
            '29',
            '30',
            '31',
            '32',
            '33',
            '34',
            '35',
            '36',
            '37',
            '38'
        ]
    },
    british: {
        name: "British",
        varName: 'british',
        values: [
            'S',
            'HS',
            'VS',
            'HVS',
            'E1',
            'E2',
            'E3',
            'E4',
            'E5',
            'E6',
            'E7',
            'E8',
            'E9',
            'E10',
            'E11',
            'E11 7b'
        ]
    }
}

export const BoulderDifficulty = {
    vScale: {
        name: "V-Scale",
        varName: 'vScale',
        values: [
            'V0',
            'V0', // two of these because V0 covers both 4 and 4+ on the french scale
            'V1',
            'V1', // same idea here, V1 covers 5 and 5+ on the french scale
            'V2',
            'V3',
            'V4',
            'V5',
            'V6',
            'V7',
            'V8',
            'V9',
            'V10',
            'V11',
            'V12',
            'V13',
            'V14',
            'V15',
            'V16'
        ]
    },
    font: {
        name: 'Font (French)',
        varName: 'font',
        values: [
            '4',
            '4+',
            '5',
            '5+',
            '6a',
            '6a+',
            '6b',
            '6b+',
            '6c',
            '6c+',
            '7a',
            '7a+',
            '7b',
            '7b+',
            '7c',
            '7c+',
            '8a',
            '8a+',
            '8b',
            '8b+',
            '8c',
            '8c+',
        ]
    }
}